use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(BlogPosts::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BlogPosts::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(BlogPosts::TenantId).uuid().not_null())
                    .col(ColumnDef::new(BlogPosts::AuthorId).uuid().not_null())
                    .col(ColumnDef::new(BlogPosts::CategoryId).uuid())
                    .col(
                        ColumnDef::new(BlogPosts::Status)
                            .string_len(32)
                            .not_null()
                            .default("draft"),
                    )
                    .col(ColumnDef::new(BlogPosts::Slug).string_len(255).not_null())
                    .col(
                        ColumnDef::new(BlogPosts::Metadata)
                            .json_binary()
                            .not_null()
                            .default("{}"),
                    )
                    .col(ColumnDef::new(BlogPosts::FeaturedImageUrl).text())
                    .col(ColumnDef::new(BlogPosts::PublishedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(BlogPosts::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BlogPosts::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(BlogPosts::ArchivedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(BlogPosts::CommentCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BlogPosts::ViewCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BlogPosts::Version)
                            .integer()
                            .not_null()
                            .default(1),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_blog_posts_tenant_slug")
                    .table(BlogPosts::Table)
                    .col(BlogPosts::TenantId)
                    .col(BlogPosts::Slug)
                    .unique()
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_blog_posts_status_published_at")
                    .table(BlogPosts::Table)
                    .col(BlogPosts::TenantId)
                    .col(BlogPosts::Status)
                    .col(BlogPosts::PublishedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_blog_posts_category_published_at")
                    .table(BlogPosts::Table)
                    .col(BlogPosts::TenantId)
                    .col(BlogPosts::CategoryId)
                    .col(BlogPosts::PublishedAt)
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(BlogPostTranslations::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BlogPostTranslations::Id)
                            .uuid()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BlogPostTranslations::PostId)
                            .uuid()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BlogPostTranslations::Locale)
                            .string_len(16)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BlogPostTranslations::Title)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BlogPostTranslations::Excerpt).text())
                    .col(ColumnDef::new(BlogPostTranslations::SeoTitle).text())
                    .col(ColumnDef::new(BlogPostTranslations::SeoDescription).text())
                    .col(ColumnDef::new(BlogPostTranslations::Body).text().not_null())
                    .col(
                        ColumnDef::new(BlogPostTranslations::BodyFormat)
                            .string_len(32)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BlogPostTranslations::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BlogPostTranslations::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_blog_post_translations_post")
                            .from(BlogPostTranslations::Table, BlogPostTranslations::PostId)
                            .to(BlogPosts::Table, BlogPosts::Id)
                            .on_update(ForeignKeyAction::Cascade)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_blog_post_translations_post_locale")
                    .table(BlogPostTranslations::Table)
                    .col(BlogPostTranslations::PostId)
                    .col(BlogPostTranslations::Locale)
                    .unique()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(BlogPostTranslations::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(BlogPosts::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(DeriveIden)]
enum BlogPosts {
    Table,
    Id,
    TenantId,
    AuthorId,
    CategoryId,
    Status,
    Slug,
    Metadata,
    FeaturedImageUrl,
    PublishedAt,
    CreatedAt,
    UpdatedAt,
    ArchivedAt,
    CommentCount,
    ViewCount,
    Version,
}

#[derive(DeriveIden)]
enum BlogPostTranslations {
    Table,
    Id,
    PostId,
    Locale,
    Title,
    Excerpt,
    SeoTitle,
    SeoDescription,
    Body,
    BodyFormat,
    CreatedAt,
    UpdatedAt,
}
