// Locale management is now handled by leptos_i18n via I18nContextProvider.
// See crate::i18n::* (generated by build.rs from locales/en.json and locales/ru.json).
//
// Old self-written i18n (shared::i18n) is deprecated.
// Use: crate::{use_i18n, t, t_string, Locale, I18nContextProvider}
