use super::*;

pub(crate) fn validate_module_local_docs_contract(slug: &str, module_root: &Path) -> Result<()> {
    validate_module_local_docs_file(
        slug,
        &module_root.join("docs").join("README.md"),
        &[
            "## Назначение",
            "## Зона ответственности",
            "## Интеграция",
            "## Проверка",
            "## Связанные документы",
        ],
    )?;
    validate_module_local_docs_file(
        slug,
        &module_root.join("docs").join("implementation-plan.md"),
        &[
            "## Область работ",
            "## Текущее состояние",
            "## Этапы",
            "## Проверка",
            "## Правила обновления",
        ],
    )?;

    Ok(())
}

pub(crate) fn generate_registry() -> Result<()> {
    println!("Generating ModuleRegistry from modules.toml...");

    let manifest = load_manifest()?;
    let output_path = Path::new("apps/server/src/modules/generated.rs");

    fs::create_dir_all(output_path.parent().unwrap())
        .context("Failed to create modules directory")?;

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by `cargo xtask generate-registry`\n");
    code.push_str("// DO NOT EDIT MANUALLY\n");
    code.push_str("// Generated from modules.toml\n\n");
    code.push_str("use rustok_core::ModuleRegistry;\n\n");

    for (slug, spec) in &manifest.modules {
        let module_struct = to_pascal_case(slug);
        let crate_name = spec.crate_name.replace("-", "_");
        code.push_str(&format!("use {}::{}Module;\n", crate_name, module_struct));
    }

    code.push_str("\n/// Build ModuleRegistry from configured modules\n");
    code.push_str("pub fn build_registry() -> ModuleRegistry {\n");
    code.push_str("    let mut registry = ModuleRegistry::new();\n\n");

    for slug in manifest.modules.keys() {
        let module_struct = to_pascal_case(slug);
        code.push_str(&format!("    // Register {} module\n", slug));
        code.push_str(&format!(
            "    registry.register(Box::new({}Module::new()));\n\n",
            module_struct
        ));
    }

    code.push_str("    registry\n");
    code.push_str("}\n");

    fs::write(output_path, code).context("Failed to write generated.rs")?;

    println!("[ok] Generated: {}", output_path.display());
    println!("  Registered {} modules", manifest.modules.len());

    Ok(())
}

pub(crate) fn validate_manifest() -> Result<()> {
    println!("Validating modules.toml and rustok-module.toml...");

    let manifest_path = manifest_path();
    let manifest = load_manifest_from(&manifest_path)?;
    let installed = manifest.modules.keys().cloned().collect::<HashSet<_>>();

    let missing_defaults = manifest
        .settings
        .as_ref()
        .and_then(|settings| settings.default_enabled.as_ref())
        .into_iter()
        .flatten()
        .filter(|slug| !installed.contains(*slug))
        .cloned()
        .collect::<Vec<_>>();

    if !missing_defaults.is_empty() {
        anyhow::bail!(
            "default_enabled contains modules not present in modules.toml: {}",
            missing_defaults.join(", ")
        );
    }

    validate_default_enabled_server_contract(&manifest_path, &manifest)?;
    validate_host_ui_inventory_contract(&manifest_path, &manifest)?;
    validate_server_event_runtime_contract(&manifest_path)?;

    let mut module_manifest_count = 0usize;

    for (slug, spec) in &manifest.modules {
        match spec.source.as_str() {
            "path" => {
                if spec.path.is_none() {
                    anyhow::bail!("Module '{}' has source='path' but no path specified", slug);
                }
            }
            "git" => {
                if spec.git.is_none() {
                    anyhow::bail!(
                        "Module '{}' has source='git' but no git URL specified",
                        slug
                    );
                }
            }
            "registry" | "crates-io" => {
                if spec.version.is_none() {
                    anyhow::bail!(
                        "Module '{}' has source='{}' but no version specified",
                        slug,
                        spec.source
                    );
                }
            }
            other => anyhow::bail!("Module '{}' has invalid source '{}'", slug, other),
        }

        let missing_dependencies = spec
            .depends_on
            .as_deref()
            .unwrap_or_default()
            .iter()
            .filter(|dependency| !installed.contains(*dependency))
            .cloned()
            .collect::<Vec<_>>();

        if !missing_dependencies.is_empty() {
            anyhow::bail!(
                "Module '{}' depends on missing modules: {}",
                slug,
                missing_dependencies.join(", ")
            );
        }

        if spec.source == "path" {
            let package_path =
                module_package_manifest_path(&manifest_path, spec).with_context(|| {
                    format!("Module '{}' has source='path' but no path specified", slug)
                })?;
            if !package_path.exists() {
                anyhow::bail!(
                    "Module '{}' requires rustok-module.toml at {}",
                    slug,
                    package_path.display()
                );
            }

            let package_manifest = load_module_package_manifest(&package_path)?;
            validate_module_package_metadata(slug, &package_manifest.module)?;
            validate_module_semantics_contract(slug, spec, &package_manifest.module)?;
            let module_root = package_path.parent().with_context(|| {
                format!(
                    "Failed to resolve module root for '{}'",
                    package_path.display()
                )
            })?;
            validate_module_event_listener_contract(slug, module_root)?;
            module_manifest_count += 1;
        }
    }

    println!("[ok] Manifest is valid");
    println!("  Schema: {}", manifest.schema);
    println!("  Modules: {}", manifest.modules.len());
    println!("  Module manifests: {}", module_manifest_count);

    Ok(())
}

pub(crate) fn list_modules() -> Result<()> {
    let manifest = load_manifest()?;

    println!("Configured modules:");
    println!();

    for (slug, spec) in &manifest.modules {
        println!("  {}:", slug);
        println!("    crate: {}", spec.crate_name);
        println!("    source: {}", spec.source);
        if let Some(ref path) = spec.path {
            println!("    path: {}", path);
        }
        if let Some(ref version) = spec.version {
            println!("    version: {}", version);
        }
        if let Some(ref depends_on) = spec.depends_on {
            println!("    depends_on: {:?}", depends_on);
        }
        println!();
    }

    Ok(())
}
